//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConferenceCalls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyConferenceCalls.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application information.
        /// </summary>
        public static string ApplicationInformation {
            get {
                return ResourceManager.GetString("ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY CONFERENCE CALLS.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Conference Calls for Windows® Phone.
        /// </summary>
        public static string ApplicationTitleLong {
            get {
                return ResourceManager.GetString("ApplicationTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Conference Calls.
        /// </summary>
        public static string ApplicationTitleNormal {
            get {
                return ResourceManager.GetString("ApplicationTitleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attendees.
        /// </summary>
        public static string Attendees {
            get {
                return ResourceManager.GetString("Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial-in number.
        /// </summary>
        public static string ConferenceNumber {
            get {
                return ResourceManager.GetString("ConferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConferenceNumberExample {
            get {
                return ResourceManager.GetString("ConferenceNumberExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the dial-in number of your conference hub. .
        /// </summary>
        public static string ConferenceNumberHelp {
            get {
                return ResourceManager.GetString("ConferenceNumberHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 NavaTron Corporation. All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@navatron.com.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick-off todays calls fast and safe while on the road. You don’t need to dial conference phone numbers,  meeting IDs, or PINs..
        /// </summary>
        public static string HelpBody1 {
            get {
                return ResourceManager.GetString("HelpBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your name matches the organizer name of the meeting, you are connected as Leader. Your dial-in number is used to call the conference hub. All other information is retrieved from your agenda..
        /// </summary>
        public static string HelpBody2 {
            get {
                return ResourceManager.GetString("HelpBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft® OCS® 2007
        ///Microsoft® Lync® 2010
        ///GoTo Meeting®.
        /// </summary>
        public static string HelpBody3 {
            get {
                return ResourceManager.GetString("HelpBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with a single tap.
        /// </summary>
        public static string HelpTitle1 {
            get {
                return ResourceManager.GetString("HelpTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic leader detection.
        /// </summary>
        public static string HelpTitle2 {
            get {
                return ResourceManager.GetString("HelpTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported conference calls.
        /// </summary>
        public static string HelpTitle3 {
            get {
                return ResourceManager.GetString("HelpTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader name.
        /// </summary>
        public static string LeaderName {
            get {
                return ResourceManager.GetString("LeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your [Firstname Lastname]. You are connected as the Leader if there is a match with the organizer name of the meeting..
        /// </summary>
        public static string LeaderNameHelp {
            get {
                return ResourceManager.GetString("LeaderNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader pin.
        /// </summary>
        public static string LeaderPin {
            get {
                return ResourceManager.GetString("LeaderPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Leader PIN (Personal Identification Number) is used to connect you as the Leader..
        /// </summary>
        public static string LeaderPinHelp {
            get {
                return ResourceManager.GetString("LeaderPinHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location: {0}.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Microsoft Lync.
        /// </summary>
        public static string Lync {
            get {
                return ResourceManager.GetString("Lync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the Microsoft Lync client here.
        /// </summary>
        public static string LyncDownload {
            get {
                return ResourceManager.GetString("LyncDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no conference calls.
        /// </summary>
        public static string NoConferenceCalls {
            get {
                return ResourceManager.GetString("NoConferenceCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organizer: {0}.
        /// </summary>
        public static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This background agent periodically checks for Conference Calls in your calander and updates the Live Tile for this application on the start screen..
        /// </summary>
        public static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to apply the language change.
        /// </summary>
        public static string RestartForLanguage {
            get {
                return ResourceManager.GetString("RestartForLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review on Marketplace.
        /// </summary>
        public static string ReviewOnMarketplace {
            get {
                return ResourceManager.GetString("ReviewOnMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enjoy using My ConfCalls, please submit a review by clicking the button below..
        /// </summary>
        public static string ReviewText {
            get {
                return ResourceManager.GetString("ReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTile {
            get {
                return ResourceManager.GetString("SettingsPageTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For questions, bugs or feature requests, please contact us by clicking the button below..
        /// </summary>
        public static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free try mode expired. Please purchase the full version on the Marketplace, for unlimitted calls..
        /// </summary>
        public static string TryMode {
            get {
                return ResourceManager.GetString("TryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start your first call, you&apos;ll need to enter some settings. Please goto the settings page..
        /// </summary>
        public static string WarningNoDailNumber {
            get {
                return ResourceManager.GetString("WarningNoDailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
